# Generated by Django 3.2.20 on 2024-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_service_patient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='covered',
            field=models.BooleanField(default=False),
        ),
    ]
